export {
  CODINGNS_CONTROL_BASE_URL_FIELD,
  CODINGNS_CONTROL_BASE_URLS_FIELD,
  CODINGNS_CONTROL_STATION_URL,
  CODINGNS_H5_LOGIN_URL,
  CODINGNS_LAN_ACCESS_DSH_FIELD,
  CODINGNS_TERMINAL_ENHANCEMENT_FIELD,
  CODINGNS_WORKSPACE_SESSION_ENHANCEMENT_FIELD,
  CODINGNS_MODULES_FIELD,
  CODINGNS_SETTINGS_NAMESPACE,
  DEFAULT_CODINGNS_CONTROL_BASE_URL,
  DEFAULT_CODINGNS_CONTROL_BASE_URLS,
  DEFAULT_CODINGNS_SETTINGS,
  DEFAULT_QUICK_PHRASES,
  DEFAULT_TERMINAL_ENHANCEMENT_SETTINGS,
  DEFAULT_WORKSPACE_SESSION_ENHANCEMENT_SETTINGS,
  captureRestartFeatureStates,
  enabledFeatureNames,
  isFeatureDshVersionCompatible,
  isFeatureEnabled,
  type CodingNsSettings,
  type CodingNsConfig,
  type CodingNsRuntimeState,
  type CodingNsCliAdapterPreference,
  type LanAccessDshSettings,
  type LanAccessDshLoginSettings,
  type LoginProtectionScopes,
  type RestartFeatureStates,
  type TerminalAppearanceSettings,
  type TerminalAppearanceTheme,
  type TerminalBindingScope,
  type TerminalCursorStyle,
  type TerminalEnhancementSettings,
  type TerminalProfileId,
  type QuickPhrase,
  type WorkspaceSessionEnhancementSettings,
} from './contracts/config.js'
export type {
  FeatureContext,
  FeatureActivation,
  FeatureDescriptor,
  FeatureCapabilityRequirement,
  FeatureDisposer,
  FeatureModule,
  FeatureResourceScope,
  FeatureRuntime,
  FeatureState,
  FeatureUiDescriptor,
} from './contracts/feature.js'
export type {
  DshCapabilityDiagnostic,
  DshCapabilityId,
  DshCapabilityProfile,
  DshCapabilityResolution,
  DshCapabilityResolutionStatus,
  DshCapabilityRoute,
  DshCapabilityRouteStatus,
  DshCapabilityRuntime,
} from '../dsh-capabilities/types.js'
export {
  CODINGNS_DSH_ERROR_CODES,
  CodingNsDshError,
  SUPPORTED_DSH_COMPATIBILITY,
  SUPPORTED_DSH_VERSION,
  assertSupportedDshVersion,
  type CodingNsDshErrorCode,
} from './contracts/errors.js'
export {
  CODINGNS_VERSION,
  DSH_COMPATIBILITY,
  DSH_PROTOCOL_VERSION,
  CODINGNS_DSH_VERSION_GLOBAL,
  DSH_TESTED_VERSION,
  DSH_VERSION,
  isDshVersionAtLeast,
  isLegacyDshVersion,
  isDshVersionCompatible,
} from './contracts/version.js'
export type {
  CodingNsRpcRequest,
  CodingNsStreamRequest,
  CodingNsTransport,
  CodingNsTransportErrorShape,
  CodingNsTransportGeneration,
  CodingNsTransportHooks,
} from './contracts/transport.js'
export {
  DSH_ENVELOPE_PROTOCOL,
  DSH_ENVELOPE_VERSION,
  DEFAULT_MAX_DSH_ENVELOPE_BYTES,
  DEFAULT_MAX_DSH_META_BYTES,
  decodeDshEnvelope,
  encodeDshEnvelope,
  validateDshEnvelope,
  type DshChannel,
  type DshEnvelope,
  type DshEnvelopeCodecOptions,
  type DshEnvelopeFlags,
  type DshHostScope,
} from '../transport/dsh-envelope.js'
export { CODINGNS_RPC_CHANNEL } from './contracts/transport.js'
export type {
  CodingNsCliAdapterDescriptor,
  CodingNsCliAdapterId,
  CodingNsCliCapability,
  CodingNsAgentEvent,
  CodingNsAgentQuestion,
  CodingNsAgentQuestionResponse,
  CodingNsAgentToolEvent,
  CodingNsCliMessage,
  CodingNsCliModel,
  CodingNsCliModelCatalog,
  CodingNsCliModelGroup,
  CodingNsAgentPermissionResponse,
  CodingNsCliSessionConfig,
  CodingNsCliSessionRecord,
  CodingNsCliProviderSessionState,
  CodingNsCliSessionStatus,
  CodingNsSessionAdapterBinding,
  CodingNsCliTurnInput,
} from './contracts/cli-adapter.js'
export type {
  CommandCodeSubscriptionUsage,
  CommandCodeSubscriptionWindow,
} from './contracts/command-code.js'
export type {
  GitBranchItem,
  GitBranchSnapshot,
  GitChangeItem,
  GitCommitResult,
  GitDiff,
  GitHistoryItem,
  GitHistoryPage,
  GitHistoryRef,
  GitRepoSnapshot,
  GitStatus,
} from './contracts/git.js'
export type {
  CliSubscriptionProvider,
  CliSubscriptionUsage,
  CliSubscriptionWindow,
  DeepseekBalance,
  DeepseekUsage,
  ProviderBalanceUsage,
  Sub2ApiDailyUsage,
  Sub2ApiModelUsage,
  Sub2ApiUsage,
  Sub2ApiUsagePoint,
} from './contracts/subscription.js'
export type {
  PeerHostRecord,
  PeerHostStatus,
  ResourceScopeDisposer,
  ResourceScopeInput,
  ResourceScopeRef,
  ResourceScopeSnapshot,
} from './contracts/peer-host.js'
export { ResourceScopeStaleError } from './contracts/peer-host.js'
export {
  DEBUG_ERROR_CODES,
  DEBUG_RPC_ENDPOINTS,
  parseDebugMutationScope,
  parseDebugPtyLaunchRequest,
  parseDebugRpcScope,
  type DebugAiFallbackState,
  type DebugCompatibilityLevel,
  type DebugErrorCode,
  type DebugMutationScope,
  type DebugPortState,
  type DebugProcessInstance,
  type DebugProcessOwnership,
  type DebugPlanState,
  type DebugProxyProtocol,
  type DebugPtyLaunchRequest,
  type DebugRpcEndpoint,
  type DebugRpcScope,
  type DebugRuntimeMode,
  type DebugRuntimeState,
} from './contracts/debug.js'
export type {
  LanAccessDshConfig,
  LanAccessDshLoginConfig,
  LanAccessDshSnapshot,
  LanAccessDshState,
} from './contracts/lan-access-dsh.js'
export type {
  CodingNsTerminalCreateRequest,
  CodingNsTerminalEnvironment,
  CodingNsTerminalFrame,
  CodingNsTerminalRetentionFrame,
  CodingNsTerminalRuntimeType,
  CodingNsTerminalShell,
  CodingNsTerminalShellOption,
  CodingNsTerminalStatus,
  CodingNsTerminalState,
  CodingNsWebTerminalInfo,
  PersistentTerminalRecord,
  TerminalAttachmentRecord,
  TerminalOwnerScope,
  TerminalRecordIdentity,
} from './contracts/terminal.js'
export {
  EMPTY_DEBUG_CONFIG,
  parseDebugConfig,
  type DebugConfig,
  type DebugProfile,
  type DebugProxyConfig,
  type DebugRuntimeType,
  type DebugShell,
} from './contracts/debug-config.js'
export type {
  DshDeviceSummary,
  DshDeviceRegistrationRequest,
  DshDeviceRegistrationResponse,
  DshDeviceListResponse,
  DshDeviceHeartbeatResponse,
  DshDeviceHeartbeatRequest,
  DshRelayTicketRequest,
  DshRelayTicketResponse,
  DshRelayTicketLike,
  DshIceServer,
  DshDeviceCredentialRecord,
} from './contracts/dsh-device.js'
export type {
  TerminalLaunchProfile,
  TerminalProcessInstance,
  TerminalProcessLaunchRequest,
  TerminalProcessLaunchResult,
  TerminalProcessState,
} from './contracts/terminal-process.js'
export type {
  AccountProfile,
  AuthClientType,
  AuthDeviceManagementSnapshotDto,
  AuthDeviceViewDto,
  CodingNsAuthLoginResult,
  CodingNsAuthSessionSnapshot,
  CodingNsAuthStatus,
  HostBindRequest,
  HostBindResponse,
  HostBindingsResponse,
  HostLabelAvailabilityResponse,
  HostUnbindResponse,
  LoginByEmailRequest,
  TunnelBindingSummary,
} from './contracts/auth.js'
export type {
  RelayIceServer,
  RelaySignalingTicketRequest,
  RelaySignalingClientMessage,
  RelaySignalingServerMessage,
  RelaySignalingTicketResponse,
} from './contracts/signaling.js'
export type { DshHostStatus } from './contracts/host-status.js'
export {
  CODINGNS4DSH_DEBUG_ENV,
  debugInfo,
  debugWarn,
  resolveCodingNsDebugEnabled,
} from './debug.js'
